### ISSUE TITLE
  File "pose_optimization.py", line 287, in find_optimal_pose     vertices=torch.matmul(vertices.unsqueeze(0), rotations_init), RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#29]
In my Ubuntu 20.04 machine, the same exact command produces correct results however in my CentOS 7 I get the following error. Could you please help me figure what's wrong? 

CentOS 7: NVIDIA driver version 460.67, CUDA 11.2, Python 3.6.8, PyTorch 1.8.1+cu111

Ubuntu 20.04 machine: NVIDIA driver 460.39, CUDA 11.2, PyTorch 1.8.1+cu111, Python 3.8.5

```
(phosa) [jalal@goku phosa]$ python demo.py --filename input/bat_sidehold.jpg --class_name bat
2021-03-30 14:12:47,811 INFO     Calling with args: Namespace(class_name='bat', filename='input/bat_sidehold.jpg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2021-03-30 14:12:50,740 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-30 14:12:50,744 INFO     URL https://dl.fbaipublicfiles.com/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl cached in /home/grad3/jalal/.torch/fvcore_cache/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-30 14:12:50,893 INFO     Reading a file from 'Detectron2 Model Zoo'
WARNING: You are using a SMPL model, with only 10 shape coefficients.
class_name:  bat
  0%|                                                                                                  | 0/12500.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "demo.py", line 145, in <module>
    main(get_args())
  File "demo.py", line 121, in main
    instances=instances, class_name=args.class_name, mesh_index=args.mesh_index
  File "/scratch3/research/code/phosa/phosa/pose_optimization.py", line 407, in find_optimal_poses
    num_initializations=num_initializations,
  File "/scratch3/research/code/phosa/phosa/pose_optimization.py", line 287, in find_optimal_pose
    vertices=torch.matmul(vertices.unsqueeze(0), rotations_init),
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
  0%|                                                                                                  | 0/12500.0 [00:00<?, ?it/s]

```

CentOS 7:

![Screenshot from 2021-03-30 14-15-38](https://user-images.githubusercontent.com/76495162/113036519-6a3ae800-9162-11eb-9bd4-a83ca8ad9a48.png)

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

Ubuntu 20.04:
![Screenshot from 2021-03-30 14-17-43](https://user-images.githubusercontent.com/76495162/113036799-b4bc6480-9162-11eb-9f9d-e4b82e4a6fb6.png)

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

I also have the following in the CentOS machine:
```
(phosa) [jalal@goku deviceQuery]$ sudo make
[sudo] password for jalal: 
/usr/local/cuda-10.2/bin/nvcc -ccbin g++ -I../../common/inc  -m64    -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 -o deviceQuery.o -c deviceQuery.cpp
/usr/local/cuda-10.2/bin/nvcc -ccbin g++   -m64      -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 -o deviceQuery deviceQuery.o 
mkdir -p ../../bin/x86_64/linux/release
cp deviceQuery ../../bin/x86_64/linux/release
(phosa) [jalal@goku deviceQuery]$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 2 CUDA Capable device(s)

Device 0: "GeForce GTX 1080 Ti"
  CUDA Driver Version / Runtime Version          11.2 / 10.2
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 11178 MBytes (11721113600 bytes)
  (28) Multiprocessors, (128) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1671 MHz (1.67 GHz)
  Memory Clock rate:                             5505 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 2883584 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 5 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 1: "GeForce GTX 1080 Ti"
  CUDA Driver Version / Runtime Version          11.2 / 10.2
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 11178 MBytes (11721506816 bytes)
  (28) Multiprocessors, (128) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1671 MHz (1.67 GHz)
  Memory Clock rate:                             5505 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 2883584 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 6 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> Peer access from GeForce GTX 1080 Ti (GPU0) -> GeForce GTX 1080 Ti (GPU1) : Yes
> Peer access from GeForce GTX 1080 Ti (GPU1) -> GeForce GTX 1080 Ti (GPU0) : Yes

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.2, CUDA Runtime Version = 10.2, NumDevs = 2
Result = PASS
```

**Comment by monacv** [comment]
I have the same exact problem in another machine which has Ubuntu 18.04:

```
$ python demo.py --filename input/bat_sidehold.jpg --class_name bat
2021-03-30 12:27:28,741 INFO     Calling with args: Namespace(class_name='bat', filename='input/bat_sidehold.jpg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2021-03-30 12:27:31,703 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-30 12:27:31,703 INFO     URL https://dl.fbaipublicfiles.com/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl cached in /home/.torch/fvcore_cache/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-30 12:27:31,864 INFO     Reading a file from 'Detectron2 Model Zoo'
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:03<00:00, 26.0MB/s]
class_name:  bat
  0%|                                                                                                  | 0/12500.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "demo.py", line 145, in <module>
    main(get_args())
  File "demo.py", line 121, in main
    instances=instances, class_name=args.class_name, mesh_index=args.mesh_index
  File "/nfs/mona/code/phosa/phosa/pose_optimization.py", line 406, in find_optimal_poses
    num_initializations=num_initializations,
  File "/nfs/mona/code/phosa/phosa/pose_optimization.py", line 287, in find_optimal_pose
    vertices=torch.matmul(vertices.unsqueeze(0), rotations_init),
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
  0%|                                                                                                  | 0/12500.0 [00:00<?, ?it/s]

```

```
$ pip list
Package                 Version
----------------------- ------------------
absl-py                 0.12.0
cachetools              4.2.1
certifi                 2020.12.5
chardet                 4.0.0
chumpy                  0.70
cloudpickle             1.6.0
cycler                  0.10.0
Cython                  0.29.22
dataclasses             0.8
decorator               4.4.2
detectron2              0.2
future                  0.18.2
fvcore                  0.1.1.post20200716
google-auth             1.28.0
google-auth-oauthlib    0.4.4
grpcio                  1.36.1
idna                    2.10
imageio                 2.9.0
importlib-metadata      3.10.0
iopath                  0.1.8
kiwisolver              1.3.1
Markdown                3.3.4
matplotlib              3.3.4
mock                    4.0.3
networkx                2.5
neural-renderer-pytorch 1.1.3
numpy                   1.19.5
oauthlib                3.1.0
opencv-python           4.5.1.48
Pillow                  8.1.2
pip                     21.0.1
pkg-resources           0.0.0
portalocker             2.3.0
protobuf                3.15.6
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycocotools             2.0.2
pydot                   1.4.2
pyparsing               2.4.7
python-dateutil         2.8.1
PyWavelets              1.1.1
PyYAML                  5.4.1
requests                2.25.1
requests-oauthlib       1.3.0
rsa                     4.7.2
scikit-image            0.17.2
scipy                   1.5.4
setuptools              39.0.1
six                     1.15.0
smplx                   0.1.26
tabulate                0.8.9
tensorboard             2.4.1
tensorboard-plugin-wit  1.8.0
termcolor               1.1.0
tifffile                2020.9.3
torch                   1.8.1+cu111
torchaudio              0.8.1
torchgeometry           0.1.2
torchvision             0.9.1+cu111
tqdm                    4.59.0
typing-extensions       3.7.4.3
urllib3                 1.26.4
Werkzeug                1.0.1
wheel                   0.36.2
yacs                    0.1.8
zipp                    3.4.1

```

![Screenshot from 2021-03-30 15-30-18](https://user-images.githubusercontent.com/76495162/113045450-dc182f00-916c-11eb-9d4e-f9b36e8dd02a.png)

```
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

```


Do you know what is causing this discrepancy?

**Comment by monacv** [comment]
In ubuntu 20.04 (working phosa) I see:
```
$ cd /usr/local/cuda/samples/1_Utilities/deviceQuery
bash: cd: /usr/local/cuda/samples/1_Utilities/deviceQuery: No such file or directory
```

When I run the same exact command in Ubuntu 20.04, it produces the correct results. Here's how the output looks like:

```
$ python demo.py --filename input/bat_sidehold.jpg --class_name bat
2021-03-30 15:34:30,186 INFO     Calling with args: Namespace(class_name='bat', filename='input/bat_sidehold.jpg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2021-03-30 15:34:34,578 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-30 15:34:34,579 INFO     URL https://dl.fbaipublicfiles.com/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl cached in /home/mona/.torch/iopath_cache/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-30 15:34:34,775 INFO     Reading a file from 'Detectron2 Model Zoo'
WARNING: You are using a SMPL model, with only 10 shape coefficients.
class_name:  bat
loss: 1.81e+03: 100%|██████████████████████████████████████████████████████████████████████| 12500/12500.0 [06:39<00:00, 31.27it/s]
Loss 18.1773: 100%|██████████████████████████████████████████████████████████████████████████████| 400/400 [02:38<00:00,  2.53it/s]
2021-03-30 15:43:55,236 INFO     Saved rendered image to output/bat_sidehold.jpg.
2021-03-30 15:43:55,247 INFO     Saved top-down image to output/bat_sidehold_top.jpg.

```

```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```


```
$ pip list
Package                 Version            Location                                                                                       
----------------------- ------------------ -----------------------------------------------------------------------------------------------
absl-py                 0.11.0             
argon2-cffi             20.1.0             
async-generator         1.10               
attrs                   20.3.0             
backcall                0.2.0              
bleach                  3.3.0              
cachetools              4.2.0              
certifi                 2020.12.5          
cffi                    1.14.5             
chardet                 4.0.0              
chumpy                  0.70               
click                   7.1.2              
cloudpickle             1.6.0              
cycler                  0.10.0             
Cython                  0.29.21            
decorator               4.4.2              
defusedxml              0.7.1              
detectron2              0.4+cu111          
easydict                1.9                
entrypoints             0.3                
faster-rcnn             0.1                /home/mona/research/code/phosa/external/frankmocap/detectors/hand_object_detector/lib
filelock                3.0.12             
Flask                   1.1.2              
future                  0.18.2             
fvcore                  0.1.3.post20210311 
gdown                   3.12.2             
google-auth             1.24.0             
google-auth-oauthlib    0.4.2              
grpcio                  1.34.1             
idna                    2.10               
imageio                 2.9.0              
iopath                  0.1.2              
ipykernel               5.5.0              
ipython                 7.21.0             
ipython-genutils        0.2.0              
ipywidgets              7.6.3              
itsdangerous            1.1.0              
jedi                    0.18.0             
Jinja2                  2.11.3             
joblib                  1.0.0              
jsonschema              3.2.0              
jupyter                 1.0.0              
jupyter-client          6.1.12             
jupyter-console         6.3.0              
jupyter-core            4.7.1              
jupyterlab-pygments     0.1.2              
jupyterlab-widgets      1.0.0              
kiwisolver              1.3.1              
Markdown                3.3.3              
MarkupSafe              1.1.1              
matplotlib              3.3.3              
mistune                 0.8.4              
mock                    4.0.3              
nbclient                0.5.3              
nbconvert               6.0.7              
nbformat                5.1.2              
nest-asyncio            1.5.1              
networkx                2.5                
neural-renderer-pytorch 1.1.3              
notebook                6.3.0              
numpy                   1.19.5             
oauthlib                3.1.0              
omegaconf               2.0.6              
opencv-python           4.5.1.48           
packaging               20.9               
pandocfilters           1.4.3              
parso                   0.8.1              
pexpect                 4.8.0              
pickleshare             0.7.5              
Pillow                  8.1.0              
pip                     20.0.2             
pkg-resources           0.0.0              
portalocker             2.0.0              
prometheus-client       0.9.0              
prompt-toolkit          3.0.18             
protobuf                3.14.0             
ptyprocess              0.7.0              
pyasn1                  0.4.8              
pyasn1-modules          0.2.8              
pycocotools             2.0.2              
pycparser               2.20               
pydot                   1.4.1              
Pygments                2.8.1              
PyOpenGL                3.1.5              
pyparsing               2.4.7              
pyrsistent              0.17.3             
PySocks                 1.7.1              
python-dateutil         2.8.1              
PyWavelets              1.1.1              
PyYAML                  5.3.1              
pyzmq                   22.0.3             
qtconsole               5.0.3              
QtPy                    1.9.0              
requests                2.25.1             
requests-oauthlib       1.3.0              
rsa                     4.7                
scikit-image            0.18.1             
scikit-learn            0.24.0             
scipy                   1.6.0              
Send2Trash              1.5.0              
setuptools              44.0.0             
six                     1.15.0             
sklearn                 0.0                
smplx                   0.1.26             
tabulate                0.8.7              
tensorboard             2.4.1              
tensorboard-plugin-wit  1.7.0              
termcolor               1.1.0              
terminado               0.9.3              
testpath                0.4.4              
threadpoolctl           2.1.0              
tifffile                2021.3.5           
torch                   1.8.1+cu111        
torchaudio              0.8.1              
torchgeometry           0.1.2              
torchvision             0.9.1+cu111        
tornado                 6.1                
tqdm                    4.56.0             
traitlets               5.0.5              
typing-extensions       3.7.4.3            
urllib3                 1.26.2             
wcwidth                 0.2.5              
webencodings            0.5.1              
Werkzeug                1.0.1              
wheel                   0.36.2             
widgetsnbextension      3.5.1              
yacs                    0.1.8              
```

```

$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
```

![Screenshot from 2021-03-30 15-47-12](https://user-images.githubusercontent.com/76495162/113047364-34e8c700-916f-11eb-997b-0b097f9083b5.png)


Specifically, as you see, I have the same CUDA and NVIDIA driver version reported in both Ubuntu 20.04 (phosa working) and Ubuntu 18.04 (phosa not working). 

In Ubuntu 18.04 I also have:

```
/usr/local/cuda/samples/1_Utilities/deviceQuery$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 4 CUDA Capable device(s)

Device 0: "GeForce GTX TITAN X"
  CUDA Driver Version / Runtime Version          11.2 / 11.0
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 12211 MBytes (12803964928 bytes)
  (24) Multiprocessors, (128) CUDA Cores/MP:     3072 CUDA Cores
  GPU Max Clock rate:                            1076 MHz (1.08 GHz)
  Memory Clock rate:                             3505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 5 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 1: "GeForce GTX TITAN X"
  CUDA Driver Version / Runtime Version          11.2 / 11.0
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 12213 MBytes (12806062080 bytes)
  (24) Multiprocessors, (128) CUDA Cores/MP:     3072 CUDA Cores
  GPU Max Clock rate:                            1076 MHz (1.08 GHz)
  Memory Clock rate:                             3505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 6 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 2: "GeForce GTX TITAN X"
  CUDA Driver Version / Runtime Version          11.2 / 11.0
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 12213 MBytes (12806062080 bytes)
  (24) Multiprocessors, (128) CUDA Cores/MP:     3072 CUDA Cores
  GPU Max Clock rate:                            1076 MHz (1.08 GHz)
  Memory Clock rate:                             3505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 9 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 3: "GeForce GTX TITAN X"
  CUDA Driver Version / Runtime Version          11.2 / 11.0
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 12213 MBytes (12806062080 bytes)
  (24) Multiprocessors, (128) CUDA Cores/MP:     3072 CUDA Cores
  GPU Max Clock rate:                            1076 MHz (1.08 GHz)
  Memory Clock rate:                             3505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 10 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> Peer access from GeForce GTX TITAN X (GPU0) -> GeForce GTX TITAN X (GPU1) : Yes
> Peer access from GeForce GTX TITAN X (GPU0) -> GeForce GTX TITAN X (GPU2) : Yes
> Peer access from GeForce GTX TITAN X (GPU0) -> GeForce GTX TITAN X (GPU3) : Yes
> Peer access from GeForce GTX TITAN X (GPU1) -> GeForce GTX TITAN X (GPU0) : Yes
> Peer access from GeForce GTX TITAN X (GPU1) -> GeForce GTX TITAN X (GPU2) : Yes
> Peer access from GeForce GTX TITAN X (GPU1) -> GeForce GTX TITAN X (GPU3) : Yes
> Peer access from GeForce GTX TITAN X (GPU2) -> GeForce GTX TITAN X (GPU0) : Yes
> Peer access from GeForce GTX TITAN X (GPU2) -> GeForce GTX TITAN X (GPU1) : Yes
> Peer access from GeForce GTX TITAN X (GPU2) -> GeForce GTX TITAN X (GPU3) : Yes
> Peer access from GeForce GTX TITAN X (GPU3) -> GeForce GTX TITAN X (GPU0) : Yes
> Peer access from GeForce GTX TITAN X (GPU3) -> GeForce GTX TITAN X (GPU1) : Yes
> Peer access from GeForce GTX TITAN X (GPU3) -> GeForce GTX TITAN X (GPU2) : Yes

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.2, CUDA Runtime Version = 11.0, NumDevs = 4
Result = PASS
```

**Comment by monacv** [comment]
In CentOS 7, installed Python 3.8.5 and installed the version of PyTorch 1.8.1 that works with CUDA 10.2, and the problem is resolved. Running with batch size 128 below.

```
(phosa) [jalal@goku phosa]$ python demo.py --filename input/bat_sidehold.jpg --class_name bat
2021-03-31 03:41:53,935 INFO     Calling with args: Namespace(class_name='bat', filename='input/bat_sidehold.jpg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2021-03-31 03:41:56,659 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-31 03:41:56,666 INFO     URL https://dl.fbaipublicfiles.com/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl cached in /home/grad3/jalal/.torch/fvcore_cache/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-31 03:41:56,806 INFO     Reading a file from 'Detectron2 Model Zoo'
WARNING: You are using a SMPL model, with only 10 shape coefficients.
class_name:  bat
  0%|                                                                                                    | 0/800.0 [00:00<?, ?it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 2.12e+03:   6%|████▋                                                                      | 50/800.0 [00:07<01:51,  6.74it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.94e+03:  12%|█████████▎                                                                | 100/800.0 [00:14<01:36,  7.25it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.94e+03:  19%|█████████████▉                                                            | 150/800.0 [00:23<01:53,  5.73it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.94e+03:  25%|██████████████████▌                                                       | 200/800.0 [00:31<01:27,  6.88it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.94e+03:  31%|███████████████████████▏                                                  | 250/800.0 [00:38<01:18,  6.97it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.94e+03:  38%|███████████████████████████▊                                              | 300/800.0 [00:45<01:11,  6.99it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.89e+03:  44%|████████████████████████████████▍                                         | 350/800.0 [00:52<01:02,  7.23it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.89e+03:  50%|█████████████████████████████████████                                     | 400/800.0 [01:00<00:55,  7.18it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.89e+03:  56%|█████████████████████████████████████████▋                                | 450/800.0 [01:07<00:48,  7.18it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.89e+03:  62%|██████████████████████████████████████████████▎                           | 500/800.0 [01:14<00:40,  7.36it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.89e+03:  69%|██████████████████████████████████████████████████▉                       | 550/800.0 [01:21<00:34,  7.27it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.89e+03:  75%|███████████████████████████████████████████████████████▌                  | 600/800.0 [01:28<00:30,  6.64it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.89e+03:  81%|████████████████████████████████████████████████████████████▏             | 650/800.0 [01:36<00:22,  6.81it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.89e+03:  88%|████████████████████████████████████████████████████████████████▊         | 700/800.0 [01:44<00:15,  6.28it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.84e+03:  94%|█████████████████████████████████████████████████████████████████████▍    | 750/800.0 [01:51<00:06,  7.16it/s]PoseOptimizer(
  (pool): MaxPool2d(kernel_size=7, stride=1, padding=3, dilation=1, ceil_mode=False)
  (renderer): Renderer()
)
loss: 1.84e+03: 100%|██████████████████████████████████████████████████████████████████████████| 800/800.0 [01:58<00:00,  6.73it/s]
Loss 8.3427: 100%|███████████████████████████████████████████████████████████████████████████████| 400/400 [02:04<00:00,  3.21it/s]
2021-03-31 03:46:01,843 INFO     Saved rendered image to output/bat_sidehold.jpg.
2021-03-31 03:46:01,854 INFO     Saved top-down image to output/bat_sidehold_top.jpg.
```
![Screenshot from 2021-03-31 03-48-22](https://user-images.githubusercontent.com/76495162/113109578-1cf75e80-91d4-11eb-858e-1f39af339a8e.png)
